### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by hyeyi** [tarakc02/tarakc02.github.io#1]
Hello. I am trying to plot a dot denesity map of the City of Miami. I followed your tutorial and was able to create a map. 
![miami_racial_map](https://user-images.githubusercontent.com/44308208/47255258-f433e200-d43b-11e8-9fa4-bb2123515b86.png)
However, it is not as accurate as I hope to be. For example, there are dots in the right side where there is Atlantic ocean. I think it is mainly because your code is based on county-level census data. But, I am trying to plot only the City of Miami. Do you have any suggestion how I can fix this problem?

For your information, I have a separate shapefile of the City of Miami and the below is the code snippet of ggplot.

ggplot() +
  geom_polygon(aes(x=long,y=lat,group=group),data=miami_shape.df,
  fill="white",color="black",alpha=0) +
  geom_sf(data = points,
                 aes(colour = race,
                 fill = race),
                 size = .1) +
  scale_color_brewer(palette = "Set1") +
  scale_fill_brewer(palette = "Set1") 

Do you perhaps let me know how to generate dots based on shapefile instead of getting geometry information from the get_acs function?

This is the shapefile information.

> miami_shape
class       : SpatialPolygonsDataFrame 
features    : 120 
extent      : -80.31811, -80.12949, 25.70901, 25.8557  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0 
variables   : 115
names       : FID_1, STATEFP, COUNTYFP, TRACTCE,       GEOID,  NAME,           NAMELSAD, MTFCC, FUNCSTAT,    ALAND,   AWATER,    INTPTLAT,     INTPTLON, Shape_Leng,   Shape_Area, ... 

This is the some attributes in the shapefile.
> names(miami_shape[1:21])
 [1] "FID_1"      "STATEFP"    "COUNTYFP"   "TRACTCE"    "GEOID"      "NAME"       "NAMELSAD"  
 [8] "MTFCC"      "FUNCSTAT"   "ALAND"      "AWATER"     "INTPTLAT"   "INTPTLON"   "Shape_Leng"
[15] "Shape_Area" "GEOID_Data" "OID_"       "OBJECTID"   "STATEFP10"  "COUNTYFP10" "TRACTCE10" 

Thank you so much!

**Comment by tarakc02** [comment]
Hi @hyeyi,
you can convert `miami_shape` to an `sf` object using `st_as_sf` from the `sf` package, as explained here: https://cran.r-project.org/web/packages/sf/vignettes/sf2.html

```
library(sf)
miami_sf <- st_as_sf(miami_shape)
```

In the example, `acs` is an `sf` object, so you should be able to proceed from there. But if the data about population by race is in a separate table, you'll need to join them in order to sample points as in the example.

**Comment by hyeyi** [comment]
Thank you so much for the suggestion. I will try it and let you know how it works.

**Comment by hyeyi** [comment]
Your suggestion solved the problem. Thanks so much for your help. God bless.
![miami_racial_map](https://user-images.githubusercontent.com/44308208/47310159-4d4e7200-d604-11e8-8952-ee1ba5d84238.png)
